In [107]:
pip install pandas

Requirement already satisfied: pandas in c:\users\home\appdata\local\programs\python\python314\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\users\home\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\home\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\home\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\home\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [108]:
import pandas as pd

In [109]:
df=pd.read_csv('F:\Data Science\Diabetes Missing Data.csv')
df

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\HOME\AppData\Local\Temp\ipykernel_6888\3018786698.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  df=pd.read_csv('F:\Data Science\Diabetes Missing Data.csv')

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [110]:
df.dtypes

Pregnant               int64
Glucose              float64
Diastolic_BP         float64
Skin_Fold            float64
Serum_Insulin        float64
BMI                  float64
Diabetes_Pedigree    float64
Age                    int64
Class                  int64
dtype: object

In [111]:
df.isnull()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,False,False,False,False,True,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False
764,False,False,False,False,True,False,False,False,False
765,False,False,False,False,False,False,False,False,False
766,False,False,False,True,True,False,False,False,False
767,False,False,False,False,True,False,False,False,False

In [112]:
df.isnull().any()

Pregnant             False
Glucose               True
Diastolic_BP          True
Skin_Fold             True
Serum_Insulin         True
BMI                   True
Diabetes_Pedigree    False
Age                  False
Class                False
dtype: bool

In [113]:
df.isnull().sum()

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [114]:
df_filled=df.fillna(0)
df_filled

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,0.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,0.0,26.6,0.351,31,0
2,8,183.0,64.0,0.0,0.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,0.0,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,0.0,0.0,30.1,0.349,47,1
767,1,93.0,70.0,31.0,0.0,30.4,0.315,23,0

In [115]:
df['new_Pregnant']=df['Pregnant']

In [116]:
df['new_pregnant']=df['Skin_Fold'].fillna(df['Skin_Fold'].mean())

df

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class,new_Pregnant,new_pregnant
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1,6,35.00000
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0,1,29.00000
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1,8,29.15342
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0,1,23.00000
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1,0,35.00000
...,...,...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0,10,48.00000
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0,2,27.00000
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0,5,23.00000
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1,1,29.15342
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0,1,31.00000

In [117]:
#renaming columns

df.rename(columns={'Pregnant':'Pre'})
df.head

<bound method NDFrame.head of      Pregnant  Glucose  Diastolic_BP  Skin_Fold  Serum_Insulin   BMI  \
0           6    148.0          72.0       35.0            NaN  33.6
1           1     85.0          66.0       29.0            NaN  26.6
2           8    183.0          64.0        NaN            NaN  23.3
3           1     89.0          66.0       23.0           94.0  28.1
4           0    137.0          40.0       35.0          168.0  43.1
..        ...      ...           ...        ...            ...   ...
763        10    101.0          76.0       48.0          180.0  32.9
764         2    122.0          70.0       27.0            NaN  36.8
765         5    121.0          72.0       23.0          112.0  26.2
766         1    126.0          60.0        NaN            NaN  30.1
767         1     93.0          70.0       31.0            NaN  30.4

     Diabetes_Pedigree  Age  Class  new_Pregnant  new_pregnant
0                0.627   50      1             6      35.00000
1                0.351   31      0             1      29.00000
2                0.672   32      1             8      29.15342
3                0.167   21      0             1      23.00000
4                2.288   33      1             0      35.00000
..                 ...  ...    ...           ...           ...
763              0.171   63      0            10      48.00000
764              0.340   27      0             2      27.00000
765              0.245   30      0             5      23.00000
766              0.349   47      1             1      29.15342
767              0.315   23      0             1      31.00000

[768 rows x 11 columns]>

In [118]:
#changing datatypes
df.dtypes

Pregnant               int64
Glucose              float64
Diastolic_BP         float64
Skin_Fold            float64
Serum_Insulin        float64
BMI                  float64
Diabetes_Pedigree    float64
Age                    int64
Class                  int64
new_Pregnant           int64
new_pregnant         float64
dtype: object

In [119]:
df['Glucose'].isnull().sum()

np.int64(5)

In [120]:
df['new_glucose']=df['Glucose'].fillna(df['Glucose'].mean()).astype(int)
df.head

<bound method NDFrame.head of      Pregnant  Glucose  Diastolic_BP  Skin_Fold  Serum_Insulin   BMI  \
0           6    148.0          72.0       35.0            NaN  33.6
1           1     85.0          66.0       29.0            NaN  26.6
2           8    183.0          64.0        NaN            NaN  23.3
3           1     89.0          66.0       23.0           94.0  28.1
4           0    137.0          40.0       35.0          168.0  43.1
..        ...      ...           ...        ...            ...   ...
763        10    101.0          76.0       48.0          180.0  32.9
764         2    122.0          70.0       27.0            NaN  36.8
765         5    121.0          72.0       23.0          112.0  26.2
766         1    126.0          60.0        NaN            NaN  30.1
767         1     93.0          70.0       31.0            NaN  30.4

     Diabetes_Pedigree  Age  Class  new_Pregnant  new_pregnant  new_glucose
0                0.627   50      1             6      35.00000          148
1                0.351   31      0             1      29.00000           85
2                0.672   32      1             8      29.15342          183
3                0.167   21      0             1      23.00000           89
4                2.288   33      1             0      35.00000          137
..                 ...  ...    ...           ...           ...          ...
763              0.171   63      0            10      48.00000          101
764              0.340   27      0             2      27.00000          122
765              0.245   30      0             5      23.00000          121
766              0.349   47      1             1      29.15342          126
767              0.315   23      0             1      31.00000           93

[768 rows x 12 columns]>

In [121]:
# using lambda functions

df['lambda_glucose']=df['new_glucose'].apply(lambda l:l+l)
df.head()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class,new_Pregnant,new_pregnant,new_glucose,lambda_glucose
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1,6,35.00000,148,296
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0,1,29.00000,85,170
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1,8,29.15342,183,366
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0,1,23.00000,89,178
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1,0,35.00000,137,274

In [122]:

df=pd.read_csv('F:\Data Science\car-sales-extended-missing-data.csv')
df.head()

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\HOME\AppData\Local\Temp\ipykernel_6888\3539258947.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  df=pd.read_csv('F:\Data Science\car-sales-extended-missing-data.csv')

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [123]:
df.isnull().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [124]:
make_grouped=df.groupby('Make')['Doors'].mean()
make_grouped

Make
BMW       4.548387
Honda     4.000000
Nissan    3.782857
Toyota    4.000000
Name: Doors, dtype: float64

In [125]:
sum_grouped=df.groupby(['Colour','Make'])['Doors'].sum()
sum_grouped

Colour  Make
Black   BMW        34.0
        Honda     108.0
        Nissan     52.0
        Toyota    148.0
Blue    BMW       126.0
        Honda     332.0
        Nissan    188.0
        Toyota    428.0
Green   BMW        30.0
        Honda      72.0
        Nissan     59.0
        Toyota    120.0
Red     BMW        60.0
        Honda      88.0
        Nissan     60.0
        Toyota    116.0
White   BMW       150.0
        Honda     420.0
        Nissan    288.0
        Toyota    564.0
Name: Doors, dtype: float64

In [126]:
sum_grouped=df.groupby(['Colour','Make'])['Doors'].mean()
sum_grouped

Colour  Make
Black   BMW       4.250000
        Honda     4.000000
        Nissan    4.000000
        Toyota    4.000000
Blue    BMW       4.200000
        Honda     4.000000
        Nissan    3.686275
        Toyota    4.000000
Green   BMW       5.000000
        Honda     4.000000
        Nissan    3.687500
        Toyota    4.000000
Red     BMW       5.000000
        Honda     4.000000
        Nissan    3.750000
        Toyota    4.000000
White   BMW       4.687500
        Honda     4.000000
        Nissan    3.840000
        Toyota    4.000000
Name: Doors, dtype: float64

In [127]:
#Multiple aggregate functions
multi_grouped=df.groupby('Make')['Doors'].agg(['mean','sum','count'])
multi_grouped

            mean     sum  count
Make
BMW     4.548387   423.0     93
Honda   4.000000  1104.0    276
Nissan  3.782857   662.0    175
Toyota  4.000000  1436.0    359

In [141]:
df1=pd.DataFrame({
    'Key':['a','b','c'],
    'Value':[1,2,3]
})
df2=pd.DataFrame({
    'Key':['a','b','d'],
    'Value':[1,2,4]
})

In [142]:
df1

  Key  Value
0   a      1
1   b      2
2   c      3

In [143]:
df2

  Key  Value
0   a      1
1   b      2
2   d      4

In [144]:
pd.merge(df1,df2,on="Key",how="inner")

  Key  Value_x  Value_y
0   a        1        1
1   b        2        2

In [145]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value_x  Value_y
0   a      1.0      1.0
1   b      2.0      2.0
2   c      3.0      NaN
3   d      NaN      4.0

In [146]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value_x  Value_y
0   a        1      1.0
1   b        2      2.0
2   c        3      NaN

In [147]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value_x  Value_y
0   a      1.0        1
1   b      2.0        2
2   d      NaN        4