In [1]:
import pandas as pd
from io import StringIO

data = """
[
  {
    "name": "Rahul",
    "email": "rahul.sharma@example.com",
    "job_profile": "Software Developer"
  },
  {
   "name": "BHoomika",
    "email": "Bhoomi.sharma@example.com",
    "job_profile": "Software analyst"
  }
]
"""

df = pd.read_json(StringIO(data))

In [2]:
df

       name                      email         job_profile
0     Rahul   rahul.sharma@example.com  Software Developer
1  BHoomika  Bhoomi.sharma@example.com    Software analyst

In [3]:
df.to_json()

'{"name":{"0":"Rahul","1":"BHoomika"},"email":{"0":"rahul.sharma@example.com","1":"Bhoomi.sharma@example.com"},"job_profile":{"0":"Software Developer","1":"Software analyst"}}'

In [4]:
df.to_json(orient='index')

'{"0":{"name":"Rahul","email":"rahul.sharma@example.com","job_profile":"Software Developer"},"1":{"name":"BHoomika","email":"Bhoomi.sharma@example.com","job_profile":"Software analyst"}}'

In [5]:
df.to_json(orient='records')

'[{"name":"Rahul","email":"rahul.sharma@example.com","job_profile":"Software Developer"},{"name":"BHoomika","email":"Bhoomi.sharma@example.com","job_profile":"Software analyst"}]'

In [6]:
pip install html5lib

Requirement already satisfied: html5lib in c:\users\home\appdata\local\programs\python\python314\lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\home\appdata\local\programs\python\python314\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\home\appdata\local\programs\python\python314\lib\site-packages (from html5lib) (0.5.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
url="https://www.w3schools.com/html/html_tables.asp"
df=pd.read_html(url)

In [8]:
df[0]

                        Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy

In [9]:
df[1]

          Tag                                        Description
0     <table>                                    Defines a table
1        <th>                   Defines a header cell in a table
2        <tr>                           Defines a row in a table
3        <td>                          Defines a cell in a table
4   <caption>                            Defines a table caption
5  <colgroup>  Specifies a group of one or more columns in a ...
6       <col>  Specifies column properties for each column wi...
7     <thead>               Groups the header content in a table
8     <tbody>                 Groups the body content in a table
9     <tfoot>               Groups the footer content in a table

In [10]:
url="https://www.w3schools.com/html/html_tables.asp"
df=pd.read_html(url,match='Description',header=0)[0]
df

          Tag                                        Description
0     <table>                                    Defines a table
1        <th>                   Defines a header cell in a table
2        <tr>                           Defines a row in a table
3        <td>                          Defines a cell in a table
4   <caption>                            Defines a table caption
5  <colgroup>  Specifies a group of one or more columns in a ...
6       <col>  Specifies column properties for each column wi...
7     <thead>               Groups the header content in a table
8     <tbody>                 Groups the body content in a table
9     <tfoot>               Groups the footer content in a table

In [11]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\home\appdata\local\programs\python\python314\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\home\appdata\local\programs\python\python314\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
excel_file=pd.read_excel("F:\Data Science\sample_employees.xlsx")
excel_file

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\HOME\AppData\Local\Temp\ipykernel_15472\1049141877.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  excel_file=pd.read_excel("F:\Data Science\sample_employees.xlsx")

           Name                     Email         Job Profile
0  Rahul Sharma  rahul.sharma@example.com  Software Developer
1   Anita Verma   anita.verma@example.com        Data Analyst
2     Kiran Rao     kiran.rao@example.com      UI/UX Designer

In [17]:
df.to_pickle('excel_file')

In [20]:
pickle=pd.read_pickle('F:\Data Science\excel_file')
pickle

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\HOME\AppData\Local\Temp\ipykernel_15472\3707418287.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  pickle=pd.read_pickle('F:\Data Science\excel_file')

          Tag                                        Description
0     <table>                                    Defines a table
1        <th>                   Defines a header cell in a table
2        <tr>                           Defines a row in a table
3        <td>                          Defines a cell in a table
4   <caption>                            Defines a table caption
5  <colgroup>  Specifies a group of one or more columns in a ...
6       <col>  Specifies column properties for each column wi...
7     <thead>               Groups the header content in a table
8     <tbody>                 Groups the body content in a table
9     <tfoot>               Groups the footer content in a table